# data
transform:
  size_crops: [ 224, 96 ]
  nmb_samples: [ 2, 0 ]
  min_scale_crops: [ 0.25, 0.05 ]
  max_scale_crops: [ 1., 0.25 ]
  min_intersection_crops: 0.01
  jitter_strength: 1.0
  blur_strength: 1.0

# model
model:
  swin:
    embed_dim: 96
    depths: [ 2, 2, 18, 2 ]
    num_heads: [ 3, 6, 12, 24 ]
    windows_size: 7

  num_prototypes: 256
  dim_hidden: 2048
  dim_out: 256
  teacher_momentum: 0.99
  teacher_temp: 0.07
  student_temp: 0.1
  group_loss_weight: 0.5

# optim
train:
  epochs: 100
  warmup_epochs: 20
  base_lr: 1.25e-3
  warmup_lr: 2.5e-7
  min_lr: 2.5e-7
  weight_decay: 0.05
  optimizer:
    eps: 0.00000001
    betas: [ 0.9, 0.999 ]

